export const EMPLOYEE_HIERARCHY_DATA_FULL = [
    { id: 1, name: "Minan Majid", title: "Chief Executive Officer", department: "Board of Director", reportsTo: "N/A", pronouns: "(He/Him)" },
    { id: 2, name: "Nicola Burdon", title: "Financial Controller", department: "Central Services", reportsTo: "Minan Majid", pronouns: "(She/Her)" },
    { id: 3, name: "Emily Wells", title: "Head of Talent", department: "Talent", reportsTo: "Minan Majid", pronouns: "(She/Her)" },
    { id: 4, name: "Tausif Ilyas", title: "Principal Software Engineer", department: "Engineering", reportsTo: "Minan Majid", pronouns: "(He/Him)" },
    { id: 5, name: "Elma Slakovic", title: "Agile Delivery Manager", department: "Delivery", reportsTo: "Minan Majid", pronouns: "(She/Her)" },
    { id: 6, name: "Rashmi Mechineni", title: "Head of India", department: "Engineering", reportsTo: "Minan Majid", pronouns: "(She/Her)" },
    { id: 7, name: "Alex Basarab", title: "Principal Architect", department: "Engineering", reportsTo: "Minan Majid", pronouns: "(He/Him)" },
    { id: 8, name: "Ashley Moss", title: "Strategic Advisor", department: "Board of Director", reportsTo: "Minan Majid", pronouns: "(She/Her)" },
    { id: 9, name: "Ben Houghton", title: "Transformation Director", department: "Delivery", reportsTo: "Minan Majid", pronouns: "(He/Him)" },
    { id: 78, name: "Laura Kirdale", title: "Head of HR", department: "Central Services", reportsTo: "Minan Majid", pronouns: "(She/Her)" },
    { id: 11, name: "Dan Sanders", title: "Junior DevOps Engineer", department: "Central Services", reportsTo: "Alex Basarab", pronouns: "(He/Him)" },
    { id: 12, name: "Obi Mabroukeh", title: "Principal Architect", department: "Engineering", reportsTo: "Alex Basarab", pronouns: "(He/Him)" },
    { id: 13, name: "Muhammed Aziz", title: "Technical Lead", department: "Engineering", reportsTo: "Alex Basarab", pronouns: "(He/Him)" },
    { id: 14, name: "Dawid Kaminski", title: "Senior Software Engineer", department: "Engineering", reportsTo: "Tausif Ilyas", pronouns: "(He/Him)" },
    { id: 15, name: "Jimmy Chak", title: "Software Engineer", department: "Engineering", reportsTo: "Tausif Ilyas", pronouns: "(He/Him)" },
    { id: 16, name: "Kalyan Jothimurugan", title: "Junior Software Engineer", department: "Engineering", reportsTo: "Tausif Ilyas", pronouns: "(He/Him)" },
    { id: 17, name: "Seb Christie", title: "Software Engineer", department: "Engineering", reportsTo: "Tausif Ilyas", pronouns: "(He/Him)" },
    { id: 18, name: "Andy Brown", title: "Senior Software Engineer", department: "Engineering", reportsTo: "Tausif Ilyas", pronouns: "(He/Him)" },
    { id: 19, name: "Pradeep Banda", title: "Agile Delivery Lead", department: "Delivery", reportsTo: "Ben Houghton", pronouns: "(He/Him)" },
    { id: 20, name: "Gary Leach", title: "Technical Product Owner", department: "Delivery", reportsTo: "Ben Houghton", pronouns: "(He/Him)" },
    { id: 21, name: "Wesley Hornsey", title: "IT Operations Manager", department: "Central Services", reportsTo: "Ben Houghton", pronouns: "(He/Him)" },
    { id: 22, name: "Waqas Mohammad", title: "Business Analyst", department: "Delivery", reportsTo: "Pradeep Banda", pronouns: "(He/Him)" },
    { id: 23, name: "Mia Lockyer-Majid", title: "Marketing Executive", department: "Sales & Marketin", reportsTo: "Emily Wells", pronouns: "(She/Her)" },
    { id: 24, name: "Teagan Clarkson", title: "Apprentice Creative Digital Designer", department: "Sales & Marketin", reportsTo: "Emily Wells", pronouns: "(She/Her)" },
    { id: 25, name: "Meena Kumaresan", title: "Senior QA Automation Tester", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(She/Her)" },
    { id: 26, name: "Aniket Nagapure", title: "Senior Developer", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(He/Him)" },
    { id: 27, name: "Mallika Ganesh Prabhu", title: "Senior Developer", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(She/Her)" },
    { id: 28, name: "Manoj Kumar Chakravarthy", title: "Senior Developer", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(He/Him)" },
    { id: 29, name: "Prince Paraste", title: "Senior Software Developer", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(He/Him)" },
    { id: 30, name: "Sai Chemuturi", title: "Quality Assurance Engineer", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(He/Him)" },
    { id: 31, name: "Harthik Yadagiri", title: "Operations Executive", department: "Central Services", reportsTo: "Rashmi Mechineni", pronouns: "(He/Him)" },
    { id: 32, name: "Eswar Boyana", title: "Business Analyst", department: "Delivery", reportsTo: "Rashmi Mechineni", pronouns: "(He/Him)" },
    { id: 33, name: "Mohana Palanisamy", title: "Quality Assurance Manager", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(She/Her)" },
    { id: 34, name: "Sanooja Chandrasenan", title: "Quality Assurance Analyst", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(She/Her)" },
    { id: 35, name: "Pooja Kulkarni", title: "Software Engineer", department: "Engineering", reportsTo: "Rashmi Mechineni", pronouns: "(She/Her)" },
    { id: 36, name: "Rakshitha Gollapalli", title: "Junior Developer", department: "Engineering", reportsTo: "Aniket Nagapure", pronouns: "(She/Her)" },
    { id: 37, name: "Shraddha Nimbalkar", title: "Quality Assurance Engineer", department: "Engineering", reportsTo: "Aniket Nagapure", pronouns: "(She/Her)" },
    { id: 38, name: "Shubham Magrde", title: "Junior Software Developer", department: "Engineering", reportsTo: "Aniket Nagapure", pronouns: "(He/Him)" },
    { id: 39, name: "Sneha Choudhari", title: "Junior Developer", department: "Engineering", reportsTo: "Aniket Nagapure", pronouns: "(She/Her)" },
    { id: 40, name: "Suruthi Raj", title: "Software Engineer", department: "Engineering", reportsTo: "Aniket Nagapure", pronouns: "(She/Her)" },
    { id: 41, name: "Sanketh Suresh", title: "Software Engineer", department: "Engineering", reportsTo: "Aniket Nagapure", pronouns: "(He/Him)" },
    { id: 42, name: "Disha Wadne", title: "Junior Developer", department: "Engineering", reportsTo: "Mallika Ganesh Prabhu", pronouns: "(She/Her)" },
    { id: 43, name: "Nikita Yadav", title: "Junior Software Developer", department: "Engineering", reportsTo: "Mallika Ganesh Prabhu", pronouns: "(She/Her)" },
    { id: 44, name: "Vyshnavi Kasinadhuni", title: "Software Developer", department: "Engineering", reportsTo: "Mallika Ganesh Prabhu", pronouns: "(She/Her)" },
    { id: 45, name: "Swathi Baskar", title: "Junior Developer", department: "Engineering", reportsTo: "Mallika Ganesh Prabhu", pronouns: "(She/Her)" },
    { id: 46, name: "Megha Meshram", title: "Business Analyst", department: "Delivery", reportsTo: "Mallika Ganesh Prabhu", pronouns: "(She/Her)" },
    { id: 47, name: "Gangadharan Jeyaseelan", title: "Junior Developer", department: "Engineering", reportsTo: "Manoj Kumar Chakravarthy", pronouns: "(He/Him)" },
    { id: 48, name: "Guru Ganesan", title: "Software Engineer", department: "Engineering", reportsTo: "Manoj Kumar Chakravarthy", pronouns: "(He/Him)" },
    { id: 49, name: "Meghana Dharmaraj", title: "Quality Assurance Engineer", department: "Engineering", reportsTo: "Manoj Kumar Chakravarthy", pronouns: "(She/Her)" },
    { id: 50, name: "Priti Gaikwad", title: "Junior Software Developer", department: "Engineering", reportsTo: "Manoj Kumar Chakravarthy", pronouns: "(She/Her)" },
    { id: 51, name: "Sinchana Gowda", title: "Software Developer", department: "Engineering", reportsTo: "Manoj Kumar Chakravarthy", pronouns: "(She/Her)" },
    { id: 52, name: "Swathi Premachandran", title: "Software Developer", department: "Engineering", reportsTo: "Manoj Kumar Chakravarthy", pronouns: "(She/Her)" },
    { id: 53, name: "John Lamb", title: "QA Automation Tester", department: "Engineering", reportsTo: "Meena Kumaresan", pronouns: "(He/Him)" },
    { id: 54, name: "Karthika Kesavaraj", title: "Junior QA Automation Tester", department: "Engineering", reportsTo: "Meena Kumaresan", pronouns: "(She/Her)" },
    { id: 55, name: "Karishmaa Thivakaran", title: "Junior Developer", department: "Engineering", reportsTo: "Prince Paraste", pronouns: "(She/Her)" },
    { id: 56, name: "Madiha Aftab", title: "Junior Software Developer", department: "Engineering", reportsTo: "Prince Paraste", pronouns: "(She/Her)" },
    { id: 57, name: "Sachin Charles", title: "Software Developer", department: "Engineering", reportsTo: "Prince Paraste", pronouns: "(He/Him)" },
    { id: 58, name: "Vaishnavi Gopinath", title: "Senior Developer", department: "Engineering", reportsTo: "Prince Paraste", pronouns: "(She/Her)" },
    { id: 59, name: "Advaitha Vyayavaram", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(She/Her)" },
    { id: 60, name: "Banu Ailneni", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(She/Her)" },
    { id: 61, name: "Krish Patel", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 62, name: "Poonam Jamadar", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(She/Her)" },
    { id: 63, name: "Prajakta Dalvi", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(She/Her)" },
    { id: 64, name: "Pranav Dev", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 65, name: "Prasanth Poluparthi", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 66, name: "Ridha Hakeem", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(She/Her)" },
    { id: 67, name: "Rohit Theurkar", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 68, name: "Sahil Mehraj", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 69, name: "Saika Maqbool", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(She/Her)" },
    { id: 70, name: "Venugopal Adicherla", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 71, name: "Shubhi Singhal", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(She/Her)" },
    { id: 72, name: "Mandar Salunke", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 73, name: "Tejaswi Puram", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(She/Her)" },
    { id: 74, name: "Soumik Mallick", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 75, name: "Yash Singh", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 76, name: "Rishi Rusia", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" },
    { id: 77, name: "Sameer Mohammed", title: "Intern", department: "Engineering", reportsTo: "Vyshnavi Kasinadhuni", pronouns: "(He/Him)" } // No comma after the last item
]; // ⭐️ CLOSING ARRAY BRACKET ADDED. This resolves the syntax error.